<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <title>THT - Take Home Test</title>

    <link rel="stylesheet" href="/css/style.css"/>
</head>
<body>


<div id="wrap">

    <div id="container">
        <div id="headerContainer">
            <header>

                <h1>Take Home Test</h1>

            </header>
        </div>
        <div class="clear"></div>

        <?php print $this->content; ?>

    </div>


</div>


<div id="footerContainer">
    <footer>
        <!-- TODO: Probably put something for the footer -->
    </footer>
</div>


<script src="/js/jquery.min.js"></script>

</body>
</html>