<div id="main" role="main">

    <?php if (!empty($this->response['status']) && $this->response['status'] == 'error') { ?>
        <div class="error"><?php print $this->response['message']; ?></div>
    <?php } ?>

    <div id="loginBox">
        <div class="shadowBottom"></div>
        <div class="shadowLeft"></div>

        <form method="post" autocomplete="off" accept-charset="utf-8">

            <h1>Login</h1>

            <label for="username">Username</label>
            <input type="text" name="data[username]" value="" id="username"/>
            <label for="password">Password</label>
            <input type="password" name="data[password]" value="" id="password"/>

            <button type="submit" class="btn login">Login</button>

        </form>

    </div>


    <div class="clear"></div>

</div>
